### ISSUE TITLE
Problem running example_control_loop.py

### ISSUE THREAD

**Issue by t-little** [UniversalRobots/RTDE_Python_Client_Library#5]
I've attached a photo of the error. It occurs from the rtde_config.ConfigFile(config_filename) on line 43 of the program. 

![image](https://user-images.githubusercontent.com/97267896/179455678-07137cb4-9c61-40d2-bef0-6e4e5ff87d8c.png)

Any suggestions of points in the right direction are appreciated

**Comment by michal-milkowski** [comment]
It's likely because you're running example_control_loop.py from main folder instead of examples folder.
Version 2.7.2 is also fixing minor issue in control loop example.
