### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by slabua** [UniversalRobots/RTDE_Python_Client_Library#9]
What could cause a socket timeout and how to prevent it?
I am also not sure what information could be useful to debug it, if necessary ask for more details.
It happened after about 10-12 hours of execution.
I already tried to change the default timeout but to no avail.

```
Traceback (most recent call last):
  File "controller.py", line 288, in <module>
    main()
  File "controller.py", line 263, in main
    state = con.receive()  # <- 100 Hz requests
  File "rtde/rtde.py", line 218, in receive
    return self.__recv(Command.RTDE_DATA_PACKAGE, binary)
  File "rtde/rtde.py", line 306, in __recv
    self.__recv_to_buffer(DEFAULT_TIMEOUT)
  File "rtde/rtde.py", line 341, in __recv_to_buffer
    more = self.__sock.recv(4096)
socket.timeout: timed out
```

**Comment by michal-milkowski** [comment]
controller log from robot would be useful (/tmp/log/urcontrol/current on the robot, or URControl.log.0 in support file generated in polyscope)
+/- 20 lines around "TCPServer: RTDE client disconnected"

**Comment by slabua** [comment]
@michal-milkowski thanks for the reply, I moved to a different approach for my situation so I don't have useful data anymore.

**Comment by michal-milkowski** [comment]
Thanks for input. Reopen issue with controller logs, if it happens again.
